### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTableQuery' of undefined

### ISSUE THREAD

**Issue by kozakjefferson** [mrn3/data-ace#4]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.30.0 x64
**Electron**: 2.0.5
**OS**: Mac OS X 10.14
**Thrown From**: [data-ace](https://github.com/mrn3/data-ace) package 0.24.13

### Stack Trace

Uncaught TypeError: Cannot read property 'getTableQuery' of undefined

```
At /Users/jeffersonkozak/.atom/packages/data-ace/lib/data-ace-controller.js:322

TypeError: Cannot read property 'getTableQuery' of undefined
    at DataAceController.queryTable (/packages/data-ace/lib/data-ace-controller.js:322:69)
    at /packages/data-ace/lib/data-ace-controller.js:46:78)
    at CommandRegistry.handleCommandEvent (/private/var/folders/t7/hv20mwsx3_1f92tz3v0m9crm0000gn/T/AppTranslocation/C8625BEF-D813-4975-9A77-7809EA9CE353/d/Atom.app/Contents/Resources/app/src/command-registry.js:384:49)
    at CommandRegistry.dispatch (/private/var/folders/t7/hv20mwsx3_1f92tz3v0m9crm0000gn/T/AppTranslocation/C8625BEF-D813-4975-9A77-7809EA9CE353/d/Atom.app/Contents/Resources/app/src/command-registry.js:273:23)
    at AtomEnvironment.dispatchContextMenuCommand (/private/var/folders/t7/hv20mwsx3_1f92tz3v0m9crm0000gn/T/AppTranslocation/C8625BEF-D813-4975-9A77-7809EA9CE353/d/Atom.app/Contents/Resources/app/src/atom-environment.js:1355:25)
    at EventEmitter.outerCallback (/private/var/folders/t7/hv20mwsx3_1f92tz3v0m9crm0000gn/T/AppTranslocation/C8625BEF-D813-4975-9A77-7809EA9CE353/d/Atom.app/Contents/Resources/app/src/application-delegate.js:346:53)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
```

### Commands

```
     -0:08.0 data-ace:query-table (div.table-name)
```

### Non-Core Packages

```
autocomplete-sql 0.5.0 
build 0.70.0 
build-latex 0.0.3 
busy-signal 1.4.3 
data-ace 0.24.13 
data-atom 0.29.0 
git-control 0.9.0 
language-latex 1.1.1 
language-pgsql 0.2.3 
language-sql-mysql 0.3.1 
latex 0.50.0 
latex-autocomplete 1.1.1 
latextools 0.8.5 
s3uploader 1.1.0 
serverless-dashboard 0.2.3 
```

**Comment by mrn3** [comment]
I am sorry, I am not really supporting this project anymore, so I doubt I will get to fixing this.  You are welcome to do a pull request or even take over the project if you would like.  I have moved on to TeamSQL.

**Comment by marcelkohl** [comment]
Created a PR to solve this issue on https://github.com/mrn3/data-ace/pull/6.
The problem is when default methods are not implemented on the data-manager the plugin tries to access Promises that does not exists as default.
