### ISSUE TITLE
Uncaught TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by bladymirc** [mrn3/data-ace#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.33.0 x64
**Electron**: 2.0.11
**OS**: KDE neon
**Thrown From**: [data-ace](https://github.com/mrn3/data-ace) package 0.24.13

### Stack Trace

Uncaught TypeError: Cannot read property 'then' of undefined

```
At /home/alba/.atom/packages/data-ace/lib/data-ace-controller.js:199

TypeError: Cannot read property 'then' of undefined
    at DataAceController.onDatabaseChanged (/packages/data-ace/lib/data-ace-controller.js:199:48)
    at /packages/data-ace/lib/data-ace-controller.js:35:51
    at Function.simpleDispatch (/usr/share/atom/resources/app/static/<embedded>:11:1189772)
    at Emitter.emit (/usr/share/atom/resources/app/static/<embedded>:11:1191213)
    at DetailsHeaderView.databaseSelected (/packages/data-ace/lib/views/details-header-view.js:97:18)
    at /packages/data-ace/lib/views/details-header-view.js:27:69)
```

### Commands

```
     -0:19.1.0 data-ace:toggle-results-view (input.hidden-input)
     -0:14.7.0 data-ace:new-connection (atom-workspace.workspace.scrollbars-visible-always.theme-one-light-syntax.theme-one-light-ui)
```

### Non-Core Packages

```
data-ace 0.24.13 
```

**Comment by therbta** [comment]
I got same error!

**Comment by marcelkohl** [comment]
Created a PR to solve this issue on https://github.com/mrn3/data-ace/pull/6.
The problem is when default methods are not implemented on the data-manager the plugin tries to access Promises that does not exists as default.
